SystemOrganization addCategory: #PBManager!
SystemOrganization addCategory: #'PBManager-Announcements'!
SystemOrganization addCategory: #'PBManager-UI'!
SystemOrganization addCategory: #'PBManager-announcements'!
SystemOrganization addCategory: #'PBManager-bootstrap-extensions'!
SystemOrganization addCategory: #'PBManager-core'!
SystemOrganization addCategory: #'PBManager-image'!
SystemOrganization addCategory: #'PBManager-repository'!
