as yet unclassified
classRoles
	^{
		#ProtoObject -> #Object.
		#ProcessorScheduler -> #ProcessorScheduler.
		#Context -> #MethodContext.
		#Class -> #Class.
		#Metaclass -> #Metaclass.
		#Array -> #Array.
		#MethodDictionary -> #MethodDictionary. 
		#CompiledMethod -> #CompiledMethod.
		#Character -> #Character. 
		#ByteArray -> #ByteArray.
		#Association -> #Association.
		#BlockClosure -> #Block.
		#MethodContext -> #MethodContext.
		#Message -> #Message.
		#Point -> #Point.
		#Process -> #Process.
		#Semaphore -> #Semaphore.
		#ByteString -> #String.
		#ByteSymbol -> #Symbol.
		#True -> #True.
		#False -> #False.
		#UndefinedObject -> #UndefinedObject.
		#Float -> #Float.
		#SmallInteger -> #SmallInteger.
		#LargePositiveInteger -> #LargePositiveInteger.
		#LargeNegativeInteger -> #LargeNegativeInteger.
		#Dictionary -> #Dictionary.
		#ClassVariable -> #Association.
		#ClassInstaller -> #ClassBuilder.
		#Smalltalk -> #SmalltalkImage.
		#System -> #System
		} asDictionary