SystemOrganization addCategory: #'PBBuilder-LanguageDefinition'!
SystemOrganization addCategory: #'PBBuilder-LanguageDefinition-Core'!
SystemOrganization addCategory: #'PBBuilder-LanguageDefinition-Exceptions'!
SystemOrganization addCategory: #'PBBuilder-LanguageDefinition-Hooks'!
SystemOrganization addCategory: #'PBBuilder-LanguageDefinition-ObjVLisp'!
SystemOrganization addCategory: #'PBBuilder-LanguageDefinition-Tests'!
SystemOrganization addCategory: #'PBBuilder-LanguageDefinition-VMRequirements'!
