as yet unclassified
classRoles
	^{
		#ProcessorScheduler -> #PCProcessorScheduler.
		#Context -> #PCContext.
		#Class -> #PCClass.
		#Metaclass -> #PCMetaclass.
		#Array -> #PCArray.
		#MethodDictionary -> #PCMethodDictionary. 
		#CompiledMethod -> #PCCompiledMethod.
		#Character -> #PCCharacter. 
		#ByteArray -> #PCByteArray.
		#Association -> #PCAssociation.
		#BlockClosure -> #PCBlock.
		#MethodContext -> #PCMethodContext.
		#Point -> #PCPoint.
		#Process -> #PCProcess.
		#Semaphore -> #PCSemaphore.
		#ByteString -> #PCString.
		#ByteSymbol -> #PCSymbol.
		#True -> #PCTrue.
		#False -> #PCFalse.
		#UndefinedObject -> #PCUndefinedObject.
		#Float -> #PCFloat.
		#SmallInteger -> #PCSmallInteger.
		#LargePositiveInteger -> #PCLargePositiveInteger.
		#LargeNegativeInteger -> #PCLargeNegativeInteger.
		#Dictionary -> #PCDictionary.
	} asDictionary